-- ============================================================================
-- VitalFlow Habits Knowledge Base - Initial Seed Data
-- ============================================================================
-- High-quality habit templates and coaching wisdom for the RAG system.
-- Embeddings will be generated by the Edge Function on first use or via
-- a separate batch job.

-- Movement habits
insert into public.vitalflow_habits_knowledge (
  title, 
  body, 
  category, 
  tags, 
  goal_segments, 
  contraindications,
  default_energy_delta_kcal,
  default_time_minutes,
  difficulty_level
) values
(
  '10-Minute Morning Walk',
  'A gentle 10-minute walk outdoors or on a treadmill to wake up your metabolism and set a positive tone for the day. This low-intensity activity helps with circulation, mental clarity, and doesn''t require gym access. Perfect for recovery days or when energy is low.',
  'movement',
  array['walking', 'cardio', 'low-intensity', 'morning', 'outdoor'],
  array['fat_loss', 'stress_reduction', 'general_wellness'],
  array['severe_injury'],
  40,
  10,
  'easy'
),
(
  'Bodyweight Movement Snack (5 min)',
  'A quick 5-minute movement break with simple bodyweight exercises: 10 squats, 10 push-ups (or wall push-ups), 10 lunges per leg. Great for breaking up sedentary time and maintaining muscle engagement throughout the day.',
  'movement',
  array['bodyweight', 'strength', 'quick', 'no-equipment'],
  array['muscle_gain', 'strength', 'fat_loss'],
  array['injury', 'overtraining'],
  25,
  5,
  'easy'
),
(
  'Evening Mobility Flow (15 min)',
  'A 15-minute gentle mobility routine focusing on hips, shoulders, and spine. Includes cat-cow stretches, hip circles, shoulder rolls, and deep breathing. Excellent for recovery, sleep quality, and reducing muscle tightness from the day.',
  'movement',
  array['mobility', 'stretching', 'recovery', 'evening', 'flexibility'],
  array['recovery', 'stress_reduction', 'injury_prevention'],
  array[]::text[],
  15,
  15,
  'easy'
),
(
  'Stair Climbing Sprint (3 rounds)',
  'Three rounds of stair climbing or step-ups for 1-2 minutes each, with 1-minute rest between rounds. Excellent for cardio conditioning, leg strength, and time efficiency. Can be done at home, office, or gym.',
  'movement',
  array['cardio', 'stairs', 'hiit', 'legs', 'quick'],
  array['fat_loss', 'endurance', 'strength'],
  array['knee_injury', 'poor_sleep', 'overtraining'],
  80,
  10,
  'moderate'
),
(
  'Active Recovery Walk (20 min)',
  'A 20-minute easy-paced walk, ideally outdoors. Focus on breathing and relaxation rather than speed. Helps with recovery between intense workouts, reduces muscle soreness, and supports mental well-being.',
  'movement',
  array['walking', 'recovery', 'outdoor', 'low-intensity'],
  array['recovery', 'stress_reduction', 'fat_loss'],
  array[]::text[],
  60,
  20,
  'easy'
);

-- Nutrition habits
insert into public.vitalflow_habits_knowledge (
  title, 
  body, 
  category, 
  tags, 
  goal_segments, 
  contraindications,
  default_energy_delta_kcal,
  default_time_minutes,
  difficulty_level
) values
(
  'Protein-First Breakfast',
  'Start your day with a protein-rich breakfast containing at least 30g of protein. Examples: Greek yogurt with nuts, eggs with turkey, protein smoothie. This stabilizes blood sugar, reduces cravings, and supports muscle recovery.',
  'nutrition',
  array['protein', 'breakfast', 'meal-timing', 'satiety'],
  array['muscle_gain', 'fat_loss', 'strength'],
  array[]::text[],
  0,
  5,
  'easy'
),
(
  'Pre-Workout Snack (30 min before)',
  'Consume a small snack with 15-20g of carbs and 5-10g of protein about 30 minutes before your workout. Examples: banana with peanut butter, apple with string cheese, small protein bar. Provides energy without feeling heavy.',
  'nutrition',
  array['pre-workout', 'timing', 'energy', 'performance'],
  array['strength', 'muscle_gain', 'endurance'],
  array[]::text[],
  0,
  5,
  'easy'
),
(
  'Veggie-First Dinner Plate',
  'Build your dinner plate by filling half with vegetables first, then adding protein and carbs. This strategy increases fiber intake, improves satiety, and naturally controls portion sizes without feeling restrictive.',
  'nutrition',
  array['vegetables', 'portion-control', 'fiber', 'dinner'],
  array['fat_loss', 'general_wellness'],
  array[]::text[],
  0,
  2,
  'easy'
),
(
  'Post-Workout Protein Window (30 min)',
  'Consume 20-40g of protein within 30 minutes after strength training. This supports muscle protein synthesis and recovery. Examples: protein shake, Greek yogurt, chicken breast, or lean beef.',
  'nutrition',
  array['post-workout', 'protein', 'recovery', 'muscle-building'],
  array['muscle_gain', 'strength', 'recovery'],
  array[]::text[],
  0,
  5,
  'easy'
),
(
  'Meal Prep Sunday (2 hours)',
  'Dedicate 2 hours on Sunday to prepare 3-5 meals for the week ahead. Cook proteins in bulk, chop vegetables, and portion into containers. This habit dramatically improves adherence and reduces decision fatigue during busy weekdays.',
  'nutrition',
  array['meal-prep', 'planning', 'batch-cooking', 'weekend'],
  array['fat_loss', 'muscle_gain', 'general_wellness'],
  array[]::text[],
  0,
  120,
  'moderate'
);

-- Hydration habits
insert into public.vitalflow_habits_knowledge (
  title, 
  body, 
  category, 
  tags, 
  goal_segments, 
  contraindications,
  default_energy_delta_kcal,
  default_time_minutes,
  difficulty_level
) values
(
  'Morning Hydration Ritual (16 oz)',
  'Drink 16 oz (500ml) of water within 30 minutes of waking up, before coffee or breakfast. This rehydrates your body after sleep, jumpstarts metabolism, and supports cognitive function throughout the morning.',
  'hydration',
  array['water', 'morning', 'hydration', 'metabolism'],
  array['fat_loss', 'general_wellness', 'energy'],
  array[]::text[],
  0,
  2,
  'easy'
),
(
  'Water Bottle Refill Reminder',
  'Set a timer to refill and drink from your water bottle every 90 minutes during the day. Aim for at least 64-80 oz total. Consistent hydration improves energy, reduces hunger confusion, and supports recovery.',
  'hydration',
  array['water', 'reminder', 'consistency', 'energy'],
  array['fat_loss', 'endurance', 'general_wellness'],
  array[]::text[],
  0,
  1,
  'easy'
),
(
  'Electrolyte Boost (Workout Days)',
  'Add electrolytes (sodium, potassium, magnesium) to your water on intense workout days or when sweating heavily. This prevents cramping, supports hydration, and aids recovery. Use sugar-free electrolyte powder or add a pinch of salt.',
  'hydration',
  array['electrolytes', 'workout', 'recovery', 'performance'],
  array['endurance', 'strength', 'recovery'],
  array[]::text[],
  0,
  2,
  'easy'
);

-- Sleep habits
insert into public.vitalflow_habits_knowledge (
  title, 
  body, 
  category, 
  tags, 
  goal_segments, 
  contraindications,
  default_energy_delta_kcal,
  default_time_minutes,
  difficulty_level
) values
(
  'Screen-Free Wind-Down (30 min)',
  'Turn off all screens (phone, TV, computer) 30 minutes before your target bedtime. Replace with reading, journaling, stretching, or meditation. This improves sleep onset and quality by reducing blue light exposure.',
  'sleep',
  array['sleep-hygiene', 'wind-down', 'screen-time', 'evening'],
  array['recovery', 'stress_reduction', 'general_wellness'],
  array[]::text[],
  0,
  30,
  'moderate'
),
(
  'Consistent Bedtime Routine',
  'Go to bed at the same time every night, aiming for 7-9 hours of sleep. Consistent sleep-wake cycles optimize recovery, hormone production, and next-day performance. Set a bedtime alarm as a reminder.',
  'sleep',
  array['sleep-schedule', 'consistency', 'recovery', 'routine'],
  array['muscle_gain', 'fat_loss', 'recovery', 'stress_reduction'],
  array[]::text[],
  0,
  5,
  'moderate'
),
(
  'Cool Room Optimization',
  'Set your bedroom temperature to 65-68°F (18-20°C) for optimal sleep quality. A cooler room supports deeper sleep and better recovery. Also ensure the room is dark and quiet.',
  'sleep',
  array['sleep-environment', 'temperature', 'recovery'],
  array['recovery', 'general_wellness'],
  array[]::text[],
  0,
  2,
  'easy'
),
(
  'Magnesium Before Bed',
  'Take 200-400mg of magnesium glycinate 30-60 minutes before bed. Magnesium supports muscle relaxation, reduces cramping, and improves sleep quality. Consult a healthcare provider if you have kidney issues.',
  'sleep',
  array['supplements', 'magnesium', 'recovery', 'sleep-quality'],
  array['recovery', 'stress_reduction', 'muscle_gain'],
  array[]::text[],
  0,
  2,
  'easy'
);

-- Mindset & Recovery habits
insert into public.vitalflow_habits_knowledge (
  title, 
  body, 
  category, 
  tags, 
  goal_segments, 
  contraindications,
  default_energy_delta_kcal,
  default_time_minutes,
  difficulty_level
) values
(
  'Morning Gratitude Practice (3 min)',
  'Write down or mentally note three things you''re grateful for each morning. This simple practice shifts your mindset to a positive state, reduces stress, and improves overall well-being and motivation.',
  'mindset',
  array['gratitude', 'journaling', 'morning', 'mental-health'],
  array['stress_reduction', 'general_wellness'],
  array[]::text[],
  0,
  3,
  'easy'
),
(
  'Box Breathing Reset (5 min)',
  'Practice box breathing when stressed: inhale 4 counts, hold 4, exhale 4, hold 4. Repeat for 5 minutes. This activates the parasympathetic nervous system, reduces cortisol, and improves focus.',
  'mindset',
  array['breathing', 'stress', 'meditation', 'quick'],
  array['stress_reduction', 'recovery'],
  array[]::text[],
  0,
  5,
  'easy'
),
(
  'Progress Photo Check-In',
  'Take progress photos every 2-4 weeks in consistent lighting and poses. This provides objective feedback when scale weight doesn''t tell the full story and keeps you motivated through visual progress.',
  'mindset',
  array['tracking', 'progress', 'motivation', 'accountability'],
  array['fat_loss', 'muscle_gain'],
  array[]::text[],
  0,
  5,
  'easy'
),
(
  'Weekly Reflection & Planning',
  'Spend 15 minutes each Sunday reviewing last week''s wins and challenges, then plan your top 3 priorities for the upcoming week. This habit improves self-awareness and keeps you aligned with your goals.',
  'mindset',
  array['planning', 'reflection', 'weekly', 'goal-setting'],
  array['general_wellness', 'fat_loss', 'muscle_gain', 'strength'],
  array[]::text[],
  0,
  15,
  'moderate'
),
(
  'Cold Shower Finish (30-60 sec)',
  'End your shower with 30-60 seconds of cold water. This boosts circulation, reduces muscle soreness, improves mental resilience, and may enhance recovery. Start with 15 seconds and gradually increase.',
  'recovery',
  array['cold-therapy', 'recovery', 'circulation', 'resilience'],
  array['recovery', 'stress_reduction', 'endurance'],
  array[]::text[],
  0,
  1,
  'moderate'
),
(
  'Foam Rolling Session (10 min)',
  'Spend 10 minutes foam rolling major muscle groups: quads, hamstrings, glutes, back, and calves. Focus on tender spots for 30-60 seconds. This aids recovery, reduces soreness, and improves mobility.',
  'recovery',
  array['foam-rolling', 'myofascial-release', 'recovery', 'mobility'],
  array['recovery', 'injury_prevention', 'strength'],
  array['acute_injury'],
  15,
  10,
  'easy'
),
(
  'Meditation or Mindfulness (10 min)',
  'Practice 10 minutes of guided meditation or mindfulness. Use an app like Calm, Headspace, or simply focus on your breath. This reduces stress, improves focus, and supports overall mental health.',
  'mindset',
  array['meditation', 'mindfulness', 'stress', 'mental-health'],
  array['stress_reduction', 'general_wellness', 'recovery'],
  array[]::text[],
  0,
  10,
  'easy'
);

-- Add some more advanced/specific habits
insert into public.vitalflow_habits_knowledge (
  title, 
  body, 
  category, 
  tags, 
  goal_segments, 
  contraindications,
  default_energy_delta_kcal,
  default_time_minutes,
  difficulty_level
) values
(
  'Fasted Morning Cardio (20 min)',
  'Perform 20 minutes of low-intensity cardio (walk, bike, elliptical) before breakfast. This can enhance fat oxidation when done strategically 1-2x per week. Not suitable if you feel dizzy or weak when fasted.',
  'movement',
  array['fasted-cardio', 'fat-loss', 'morning', 'low-intensity'],
  array['fat_loss'],
  array['low_blood_sugar', 'overtraining', 'poor_sleep'],
  100,
  20,
  'moderate'
),
(
  'Calorie & Macro Tracking Check',
  'Log your food intake in your tracking app at the end of each meal. Consistent tracking improves awareness, ensures you hit protein targets, and reveals patterns that help or hurt progress.',
  'nutrition',
  array['tracking', 'accountability', 'macros', 'awareness'],
  array['fat_loss', 'muscle_gain'],
  array[]::text[],
  0,
  5,
  'moderate'
),
(
  'Caffeine Cutoff (2 PM)',
  'Stop consuming caffeine after 2 PM to protect sleep quality. Caffeine has a half-life of 5-6 hours, so late consumption can interfere with deep sleep and recovery.',
  'sleep',
  array['caffeine', 'sleep-hygiene', 'timing'],
  array['recovery', 'sleep_quality'],
  array[]::text[],
  0,
  1,
  'easy'
),
(
  'Sunrise Light Exposure (10 min)',
  'Get 10 minutes of natural sunlight exposure within 30-60 minutes of waking. This resets your circadian rhythm, improves mood, and enhances sleep quality later that night.',
  'mindset',
  array['sunlight', 'circadian', 'morning', 'vitamin-d'],
  array['general_wellness', 'recovery', 'stress_reduction'],
  array[]::text[],
  0,
  10,
  'easy'
),
(
  'Resistance Band Activation (5 min)',
  'Perform 5 minutes of resistance band exercises to activate glutes, shoulders, or core before your main workout. This improves muscle activation, reduces injury risk, and enhances performance.',
  'movement',
  array['warm-up', 'activation', 'resistance-band', 'injury-prevention'],
  array['strength', 'injury_prevention'],
  array['acute_injury'],
  10,
  5,
  'easy'
);

-- Add comment
comment on column public.vitalflow_habits_knowledge.embedding is 
  'Will be populated by Edge Function or batch job using OpenAI embeddings';

